server:
  port: 8080

kakao:
  client-key: d26bfd7ffcb2dbbf1e573e4c827d8078
  auth-url: https://kauth.kakao.com

naver:
  client-key:
  auth-url: https://nid.naver.com

--- #production phase
spring:
  config:
    activate:
      on-profile: production
  application:
    name: sels
  datasource:
    url: jdbc:mariadb://localhost:3306/self_study?useSSL=false
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
      dialect: org.hibernate.dialect.MariaDBDialect
    properties:
      hibernate:
        show-sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: DEBUG

feign:
  discord:
    webhook:
      url: https://discord.com/api/webhooks/1277101129850683415/hC94z0g-t5agjiaPuTmR9sx_-tOefW-k9De46QXr0IXodsWiinqznJgOggCbBDWbyjGt


--- #alpha phase
spring:
  config:
    activate:
      on-profile: alpha
  application:
    name: sels
  datasource:
    url: jdbc:mariadb://localhost:3306/self_study?useSSL=false
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
      dialect: org.hibernate.dialect.MariaDBDialect
    properties:
      hibernate:
        show-sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: DEBUG

feign:
  discord:
    webhook:
      url: https://discord.com/api/webhooks/1277101129850683415/hC94z0g-t5agjiaPuTmR9sx_-tOefW-k9De46QXr0IXodsWiinqznJgOggCbBDWbyjGt


--- #development phase
spring:
  config:
    activate:
      on-profile: development
  application:
    name: sels
  datasource:
    url: jdbc:mariadb://localhost:3306/self_study?useSSL=false
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
      dialect: org.hibernate.dialect.MariaDBDialect
    properties:
      hibernate:
        show-sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: DEBUG

feign:
  discord:
    webhook:
      url: https://discord.com/api/webhooks/1277101129850683415/hC94z0g-t5agjiaPuTmR9sx_-tOefW-k9De46QXr0IXodsWiinqznJgOggCbBDWbyjGt

--- #test phase
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL;
    username: SA
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show-sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect

logging:
  level:
    org.hibernate.SQL: DEBUG

feign:
  discord:
    webhook:
      url: https://discord.com/api/webhooks/1277101129850683415/hC94z0g-t5agjiaPuTmR9sx_-tOefW-k9De46QXr0IXodsWiinqznJgOggCbBDWbyjGt
