server:
  port: 8080

kakao:
  client-key: d26bfd7ffcb2dbbf1e573e4c827d8078
  auth-url: https://kauth.kakao.com

naver:
  client-key:
  auth-url: https://nid.naver.com

# TODO : redis 세팅하는데 테스트환경 redis랑 분리하기
# TODO 도커로 띄울거고 테스트 환경도 도커로, 그리고 pr할때 모든 test 돌릴 건데 git action 에서 redis 띄웠다 죽였다 할 수 있는지

--- #production phase
spring:
  config:
    activate:
      on-profile: production
  application:
    name: sels
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/self_study?useSSL=false
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
      dialect: org.hibernate.dialect.MariaDBDialect
    properties:
      hibernate:
        show-sql: true
        format_sql: true
  data:
    redis:
      host: 127.0.0.1
      port: 6379

logging:
  level:
    org.hibernate.SQL: DEBUG

feign:
  discord:
    webhook:
      url: https://discord.com/api/webhooks/1277101129850683415/hC94z0g-t5agjiaPuTmR9sx_-tOefW-k9De46QXr0IXodsWiinqznJgOggCbBDWbyjGt


--- #alpha phase
spring:
  config:
    activate:
      on-profile: alpha
  application:
    name: sels
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/self_study?useSSL=false
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
      dialect: org.hibernate.dialect.MariaDBDialect
    properties:
      hibernate:
        show-sql: true
        format_sql: true
  data:
    redis:
      host: 127.0.0.1
      port: 6379

logging:
  level:
    org.hibernate.SQL: DEBUG

feign:
  discord:
    webhook:
      url: https://discord.com/api/webhooks/1277101129850683415/hC94z0g-t5agjiaPuTmR9sx_-tOefW-k9De46QXr0IXodsWiinqznJgOggCbBDWbyjGt


--- #development phase
spring:
  config:
    activate:
      on-profile: development
  application:
    name: sels
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/self_study?useSSL=false
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
      dialect: org.hibernate.dialect.MariaDBDialect
    properties:
      hibernate:
        show-sql: true
        format_sql: true
  data:
    redis:
      host: 127.0.0.1
      port: 6379

logging:
  level:
    org.hibernate.SQL: DEBUG

feign:
  discord:
    webhook:
      url: https://discord.com/api/webhooks/1277101129850683415/hC94z0g-t5agjiaPuTmR9sx_-tOefW-k9De46QXr0IXodsWiinqznJgOggCbBDWbyjGt

--- #test phase
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL;
    username: SA
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show-sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  data:
    redis:
      host: 127.0.0.1
      port: 6379

logging:
  level:
    org.hibernate.SQL: DEBUG

feign:
  discord:
    webhook:
      url: https://discord.com/api/webhooks/1277101129850683415/hC94z0g-t5agjiaPuTmR9sx_-tOefW-k9De46QXr0IXodsWiinqznJgOggCbBDWbyjGt
